apiVersion: apps/v1
kind: Deployment
metadata:
  name: chachkies-js-deployment
spec:
  selector:
    matchLabels:
      app: chachkies-js
  template:
    metadata:
      labels:
        app: chachkies-js
    spec:
      containers:
      - name: chachkies-js
        image: ashumilov/concourse-tutorial-chachkies
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
