resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: jmkarthik/concourse-kubectl-resource
    tag: latest

resources:
- name: chachkies-source
  type: git
  source:
    uri: https://github.com/poprygun/chachkies-js.git
    branch: master

- name: chachkies-image
  type: docker-image
  source:
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-hub-username))/concourse-tutorial-chachkies

- name: chachkies-k8s
  type: kubernetes
  source:
    api_server_uri: ((server))
    namespace: ((namespace))
    certificate_authority_data: ((cad))
    token: ((token))

jobs:
- name: publish
  public: true
  serial: true
  plan:
  - get: chachkies-source
  - put: chachkies-image
    params:
      build: chachkies-source
- name: run-chachkies-in-k8s
  plan:
  - get: chachkies-source
  - put: chachkies-k8s
    params:
      file: chachkies-source/k8s/

