resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: jcderr/concourse-kubernetes-resource

resources:
- name: chachkies-source
  type: git
  source:
    uri: https://github.com/poprygun/chachkies-js.git
    branch: master

- name: chachkies-image
  type: docker-image
  source:
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-hub-username))/concourse-tutorial-chachkies

- name: chachkies-k8s
  type: kubernetes
  source:
    namespace: default
    cluster_url: https://kubernetes.default.svc
    resource_type: deployment
    resource_name: chachkies
    container_name: chachkies
    # cluster_ca: _base64 encoded CA pem_
    # admin_key: _base64 encoded key pem_
    # admin_cert: _base64 encoded certificate pem_

jobs:
- name: publish
  public: true
  serial: true
  plan:
  - get: chachkies-source
  - put: chachkies-image
    params:
      build: chachkies-source
- name: run-chachkies-in-k8s
  plan:
  - put: chachkies-k8s
    params:
      image_name: ci/image
      image_tag: ci/tag

